INSERT INTO PERSON(NAME, AGE) VALUES ('Lucas Danti', 26);
INSERT INTO PERSON(NAME, AGE) VALUES ('Marcelo Rossi', 55);
INSERT INTO PERSON(NAME, AGE) VALUES ('Luiz Boulos', 47);

INSERT INTO USER(NAME, EMAIL, USER_PASS) VALUES('Aluno', 'aluno@email.com', '$2a$10$nzyRgvd6DyqiZq6doLQvPehTXfLSj0p5HcOeo23zHRgsTFdqCwVEe');